# Generated by Django 2.1.1 on 2019-02-20 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Respondent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respondent_name', models.CharField(max_length=50)),
                ('respondent_age', models.IntegerField()),
                ('respondent_income', models.IntegerField()),
            ],
        ),
    ]
